# 微信域名
ruleset=🎯直连,[]DOMAIN,weixin.qq.com
ruleset=🎯直连,[]DOMAIN,wx.qq.com
ruleset=🎯直连,[]DOMAIN,wechat.com
# 支付宝
ruleset=🎯直连,[]DOMAIN,alipay.com
ruleset=🎯直连,[]DOMAIN,alipayobjects.com
# 网上国网
ruleset=🎯直连,[]DOMAIN,95598.cn
# 银行通用（各大银行主域名，可按需增删）
ruleset=🎯直连,[]DOMAIN,ccb.com
ruleset=🎯直连,[]DOMAIN,icbc.com.cn
ruleset=🎯直连,[]DOMAIN,abchina.com
ruleset=🎯直连,[]DOMAIN,bankcomm.com
ruleset=🎯直连,[]DOMAIN,cmbchina.com
ruleset=🎯直连,[]DOMAIN,cmbc.com.cn
ruleset=🎯直连,[]DOMAIN,spdb.com.cn
ruleset=🎯直连,[]DOMAIN,boc.cn
# 内网LAN地址直连（建议保留，不然访问NAS/路由器会走代理）
ruleset=🎯直连,[]GEOIP,LAN
# 兜底：所有其他流量全部走代理策略组
ruleset=🌐代理,[]FINAL
