# 微信域名
ruleset=🎯DIRECT,[]DOMAIN,weixin.qq.com
ruleset=🎯DIRECT,[]DOMAIN,wx.qq.com
ruleset=🎯DIRECT,[]DOMAIN,wechat.com
# 支付宝
ruleset=🎯DIRECT,[]DOMAIN,alipay.com
ruleset=🎯DIRECT,[]DOMAIN,alipayobjects.com
# 网上国网
ruleset=🎯DIRECT,[]DOMAIN,95598.cn
# 银行通用（各大银行主域名，可按需增删）
ruleset=🎯DIRECT,[]DOMAIN,ccb.com
ruleset=🎯DIRECT,[]DOMAIN,icbc.com.cn
ruleset=🎯DIRECT,[]DOMAIN,abchina.com
ruleset=🎯DIRECT,[]DOMAIN,bankcomm.com
ruleset=🎯DIRECT,[]DOMAIN,cmbchina.com
ruleset=🎯DIRECT,[]DOMAIN,cmbc.com.cn
ruleset=🎯DIRECT,[]DOMAIN,spdb.com.cn
ruleset=🎯DIRECT,[]DOMAIN,boc.cn
# 内网LAN地址直连（建议保留，不然访问NAS/路由器会走代理）
ruleset=🎯DIRECT,[]GEOIP,LAN
# 兜底：所有其他流量全部走代理策略组
ruleset=Proxy,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=Proxy`select`[]🚀节点选择[]DIRECT
